plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.fixjenni.validator"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.fixjenni.validator"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            // No signing config needed — debug keystore is auto-generated by AGP
            isDebuggable = true
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    // PDFBox-Android ships its own Bouncy Castle; exclude the duplicate to
    // avoid class-path conflicts. We bring in our own bcprov/bcpkix explicitly.
    configurations.all {
        exclude(group = "org.bouncycastle", module = "bcprov-jdk15on")
        exclude(group = "org.bouncycastle", module = "bcpkix-jdk15on")
    }

    packaging {
        resources {
            // Bouncy Castle and PDFBox both include these; keep only one copy.
            pickFirsts += listOf(
                "META-INF/BCKEY.DSA",
                "META-INF/BCKEY.SF",
                "META-INF/BC2048KE.DSA",
                "META-INF/BC2048KE.SF",
                "META-INF/LICENSE.md",
                "META-INF/NOTICE.md",
                "META-INF/LICENSE",
                "META-INF/NOTICE",
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE.txt"
            )
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.constraintlayout)

    // PDF parsing + ByteRange extraction
    implementation(libs.pdfbox.android)

    // CMS / PKCS#7 signature verification + certificate chain validation
    implementation(libs.bouncycastle.provider)
    implementation(libs.bouncycastle.pkix)
}
